### PR TITLE
Fix #66 - No way to pass timeout to database

### LINKED ISSUE #66: No way to pass timeout to database
There is no way to pass `timeout` to database, without explicitly creating connection with that timeout, and then implicitly guessing that this connection will be used for queries in that asyncio task.

Simple way to do it would be by passing `timeout` to database for e. g. `peewee_async.PostgresDatabase`, but that has two problems. 

Firstly `timeout` will be passed to psycopg2.connect that does not handle `timeout`, but `connect_timeout` which applies to database, not asyncio socket. 

Secondly it will be used correctly in `peewee_async.AsyncDatabase.connect_async`, but there timeout is already provided from argument. 

Any Idea how to go around it?
I need that feature so I will be forking `peewee_async` with simple fix, if it's acceptable I will make PR.

### PR DESCRIPTION
**Pull request by roansong**
Added `timeout` to async database connections through the connect_kwargs dict
The timeout is pulled from the connection parameters if specified therein, otherwise the default timeout is used.

### CODE REVIEW

**Comment by rudyryk** [comment]
Hello @roansong, thank you for the PR! I've looked into it and seems like it's not quite complete. Can you provide a kind of test sample?

When you modifying `connect_kwargs` via `connect_kwargs['timeout'] = timeout` it will produce side effects! That means `self.connect_kwargs_async` will change after `connect_async ()` call and that's not obvious and not intended.

**Comment by roansong** [comment]
Hi @rudyryk. Good catch! I approve of keeping things as unambiguous as possible, and will make amends. As for the test sample, I have some long-running queries that time out after 60 seconds, so I've been testing with a ```timeout``` value of 360 seconds, but a more convenient test case is below. If your queries time out almost immediately, then the change is working!

Example connection parameters:

```
from playhouse.db_url import connect

db_url = 'postgresql+pool+async://user:password@locahost:5342/testdb'
connect_params = {
    'min_connections': 1,
    'max_connections': 10,
    'timeout': 2
}
database = connect(db_url, **connect_params)
```

**Comment by roansong** [comment]
@rudyryk I'm not quite sure how to proceed without modifying the connection parameters in some way; to fit in with the ```AsyncXXXConnection``` classes and specify the timeout parameter explicitly involves popping any 'timeout' key from the ```connect_kwargs``` to avoid keyword argument clashes, which is in turn an unexpected modification.

Another possible route is to remove the ```timeout``` keyword argument from the ```AsyncXXXConnection``` classes and update it with a default value, but that requires much larger modifications across the code.

**Comment by roansong** [comment]
Note: build failure is unrelated to this PR, and is detailed in issue https://github.com/05bit/peewee-async/issues/95

**Comment by rudyryk** [comment]
Hi @roansong, I'm just not sure whether you PR is OK and this is not because of your code itself. I don't like the current implementation of peewee-async in that part because it's not clear and straightforward enough, so we would need fixes like that.

I'd consider deeper changes to make it more clear and explicit.

**Comment by rudyryk** [comment]
Sorry, need more time to review. PR's looking elegant and I like it initially but also need to double check it again to not miss a piece of puzzle. Thank you @roansong!

**Comment by roansong** [comment]
@rudyryk I've merged in the upstream changes from 0.6.0a to my fork, and have noted that instead of using `timeout` as a kwarg, use `connect_timeout`, and it works.

e.g. using
```python
database = peewee_async.PooledPostgresqlDatabase(
    database='test',
    user='user',
    host='127.0.0.1',
    port='5432',
    connect_timeout=30
)
```
or 
```python
from playhouse.db_url import connect
db_url = 'postgresql+pool+async://user@127.0.0.1:5432/test'
connect_params = {
    'connect_timeout': 30
}
database = connect(db_url, **connect_params)
```

**Comment by rudyryk** [comment]
@roansong I'm not sure why is it working? :) As I can see `aiopg` does accept `timeout` parameter but not `connect_timeout `.

**Comment by rudyryk** [comment]
Looking at `Pool` interface https://aiopg.readthedocs.io/en/stable/core.html#aiopg.create_pool

**Pull request closed without merging**
