### PR TITLE
Fix PooledMySQLDatabase.init() min_connections/max_connections arguments have no effect

### PR DESCRIPTION
**Pull request by roy2220**

### CODE REVIEW

**Comment by rudyryk** [comment]
@roy2220 Thank you for the PR! But I disagree that current design is wrong. Yes, `min_connections`  and `max_connections` is ignored for **sync** database connection but not for **async** and this is intended behaviour. The use case for `peewee-async` is asynchronous applications and sync interface is provided mainly for initialization convenience and for intermediate development state if you want to rewrite you sync code into async, so single connection should be sufficient for that.

**Comment by roy2220** [comment]
In my use case, single connection is not sufficient, all the coroutines wait for acquiring the connection (engaged while executing sql), causes low QPS

**Comment by rudyryk** [comment]
@roy2220 "In my use case, single connection is not sufficient" - hmm, async queries **are using** connection pool.

**Comment by roy2220** [comment]
Sorry, I got somethings wrong. In my situation,  
I wrote code like: (refer to the [docs](https://peewee-async.readthedocs.io/en/latest/peewee_async/api.html#peewee_async.PooledMySQLDatabase))
```
db = peewee_async.MySQLDatabase(..., max_connections=10)
```
It raises error:
```
TypeError: __init__() got an unexpected keyword argument 'max_connections'
```
So I change the code to:
```
db = peewee_async.PooledMySQLDatabase(..., max_connections=10)
```
It seems OK, but `max_connections` have no effect.
So I make this PR.

**Comment by rudyryk** [comment]
Sorry, @roy2220! I'reviewed the change closer and indeed, `PooledMySQLDatabase.init()` method has such bug.

**Pull request merged**
