### PR TITLE
Prevent connection stuck after leaving cursor unreleased

### PR DESCRIPTION
**Pull request by insolite**
Hi! I'm experiencing a connection stuck when getting unexpected peewee-level exception.
The following example will explain the issue much better:
```python
import asyncio

from peewee import Model, TimeField
from peewee_async import PostgresqlDatabase, Manager

database = PostgresqlDatabase('test', host='localhost', user='postgres')
database.set_allow_sync(False)
manager = Manager(database)


class Event(Model):

    time = TimeField()

    class Meta:
        database = database


loop = asyncio.get_event_loop()
print('start')
try:
    result1 = loop.run_until_complete(
        manager.execute(Event.select())
    )  # OverflowError here
except OverflowError:  # Ignore it
    print('OverflowError 1')
try:
    result2 = loop.run_until_complete(
        manager.execute(Event.select())
    )  # Stuck here
except OverflowError:  # Ignore it
    print('OverflowError 2')
print('finish')
```
Here is an example of throwing OverflowError when we are trying to use postgresql's `interval` field along with peewee's `TimeField`. This is obviously wrong and we get an exception when data is out of range (i. e. `"25:00:00"::interval`). But this should not break database connection in peewee.
What I've found is that there is no exception handling before cursor releasing, so the cursor become permanently locked on first exception in `fetchone()`. This was hard to find while using `PooledPostgresqlDatabase`, cause queries were hanging up randomly. But when I switched to `PostgresqlDatabase` it became clear enough.
I've made fixes to `select()` and `update()` functions. It works for me, but I probably missed something. @rudyryk could you please take a look?

### CODE REVIEW

**Comment by rudyryk** [comment]
Hi Oleg @insolite! Could you provide please SQL snippet to create `event` table? So I could test and reproduce the issue.

I'm not sure, why cursor is not released on [the line #L1481][https://github.com/05bit/peewee-async/blob/master/peewee_async.py#L1481].

**Comment by rudyryk** [comment]
Ah, I see, the exception is just occured later.

**Comment by insolite** [comment]
Sure, it is pretty simple
```SQL
CREATE TABLE "event" (
"id" SERIAL NOT NULL,
"time" interval NOT NULL,
PRIMARY KEY ("id")
)
;

INSERT INTO event (time) VALUES ('-01:00:00');
```

P. S. I did a mistake, 25 hours will not throw `OverflowError` but "-01:00:00" will do.

**Comment by rudyryk** [comment]
Great, thank you!

**Pull request merged**
