### PR TITLE
Prevent connect stuck on already failed AsyncDatabase instance

### PR DESCRIPTION
**Pull request by spumer**
When we fail connection due incorrect settings (e.g. username/password) or some connection problems we set `Database` object to fail-state which prevent re-connection.

In some cases this will be infinity stuck on **PENDING** `Future`, or infinity loop with `CancelledError`, if you try and try again connect when internal `Future` (`_async_wait`) in cancelled state.
First case i catch on Windows, second on Linux. This PR should solve root of problem.

Problem is in unsafe `Future` usage.

What do you think about that?

### CODE REVIEW

**Comment by rudyryk** [comment]
Hello @spumer!

> What do you think about that?

The current design decision based on these points:

- Fail fast when incorrect settings provided - that usually means programming error and we should not try more until error is fixed
- After dropping connection due to network error we should try to reconnect automatically

Yes, I see the point in your PR and my current code doesn't actually handles errors during settings up the connection. So I've applied your changes with modifications - I got rid of the external `tasklocals` package recently in favor of much simpler local `TaskLocals` class :)

**Comment by rudyryk** [comment]
See https://github.com/05bit/peewee-async/commit/0c47ebe4d351a9b7f28c1e2e2842bad17cf78a14

**Comment by spumer** [comment]
Lol, my mistake. I think this is because i migrate changes from older version.
Thank you!

**Comment by rudyryk** [comment]
You're welcome! Thank you! :)

**Pull request closed without merging**
