### PR TITLE
Asynchronous version of prefetch method

### LINKED ISSUE #11: Add support for prefetch() new peewee feature
https://github.com/coleifer/peewee/blob/2.7.4/peewee.py#L4754 - this line triggers sync query, seems like that we should have a separate copy-paste async version of prefetch helper.

### PR DESCRIPTION
**Pull request by cypreess**
Hi,

as @mrbox has wrote I am providing async prefetch which is working for us.  This should close #11 
We use that like that:
```
import peewee_async
products = await peewee_async.prefetch(Food.select(), Nutrition.select())
for product in products:
   print(product.nutritions_prefetch)
```

### CODE REVIEW

**Comment by rudyryk** [comment]
Hi @cypreess! Thanks you, that's great!

I think we need to add a test case wrapped in `sync_unwanted()` context just to make sure there are no implicit sync calls involved.

**Comment by cypreess** [comment]
I would really like to provide tests for prefetch but I am struggling with setting workable tests on my dev enviroment.

I got:
```
$ python setup.py test
running test
running egg_info
writing requirements to peewee_async.egg-info/requires.txt
writing dependency_links to peewee_async.egg-info/dependency_links.txt
writing peewee_async.egg-info/PKG-INFO
writing top-level names to peewee_async.egg-info/top_level.txt
reading manifest file 'peewee_async.egg-info/SOURCES.txt'
writing manifest file 'peewee_async.egg-info/SOURCES.txt'
running build_ext
test_count_query (tests.AsyncPostgresTestCase) ... /usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py:509: DeprecationWarning: asyncio.async() function is deprecated, use ensure_future()
  DeprecationWarning)
ok
test_create_obj (tests.AsyncPostgresTestCase) ... ok
test_create_uuid_obj (tests.AsyncPostgresTestCase) ... ok
test_delete_obj (tests.AsyncPostgresTestCase) ... ok
test_get_obj (tests.AsyncPostgresTestCase) ... ok
test_get_uuid_obj (tests.AsyncPostgresTestCase) ... ok
test_insert_many_rows_query (tests.AsyncPostgresTestCase) ... ok
test_insert_one_row_query (tests.AsyncPostgresTestCase) ... ok
test_insert_one_row_uuid_query (tests.AsyncPostgresTestCase) ... ok
test_scalar_query (tests.AsyncPostgresTestCase) ... ok
test_select_query (tests.AsyncPostgresTestCase) ... ok
test_update_obj (tests.AsyncPostgresTestCase) ... ok
test_update_query (tests.AsyncPostgresTestCase) ... ok
test_atomic_failed (tests.tests_py35.AsyncPostgresTransactionsTestCase)
Failed update in transaction. ... /Users/cypreess/.virtualenvs/peewee_async/lib/python3.5/site-packages/aiopg/pool.py:303: ResourceWarning: Unclosed 1 connections in <aiopg.pool.Pool object at 0x108618208>
  ResourceWarning)
FAIL
test_atomic_success (tests.tests_py35.AsyncPostgresTransactionsTestCase)
Successful update in transaction. ...
```

And test runner freeze at that point. Any help?

I was trying to change max_connection=1 to avoid pooled pg and it was even worst.

I use py35. It also seems that problem is only in py35 tests, because if I comment them tests passes

**Comment by cypreess** [comment]
OK I was able to provide tests for prefetch, (still other tests fails on my dev machine:)

**Comment by rudyryk** [comment]
@cypreess Transactions are half-working actually - not working with connection pool #14

**Pull request merged**
