### PR TITLE
Fix for Proxy database support

### PR DESCRIPTION
**Pull request by dgelvin**

### CODE REVIEW

**Comment by rudyryk** [comment]
Hi, David @dgelvin! :) Thanks for the pull request. Could you describe your use case when you need to swap a database? Actually, I was experimenting with it to run tests against all possible database drivers while reusing the test models. And I didn't try this feature in production yet.

For now, I think that the patch you've provided is OK, I just want to make sure we're moving the right direction with this particular feature :)

**Comment by rudyryk** [comment]
So, I usually pass just the same instance to `Manager` constructor as I use for model's `Meta.database`.

**Comment by dgelvin** [comment]
Sure.  So I'm not certain that I'm actually swapping databases- I was getting an exception running any query using a Proxy database without this fix.  I am running multiple unit test tests, re-initializing the database in setUp for each test, so that may be what is causing any 'swapping'.

**Comment by rudyryk** [comment]
@dgelvin Ah, I see :)

> I am running multiple unit test tests, re-initializing the database in setUp for each test ...

Well, normally, Model's (and query's) database have to be the same instance as Manager's, so it should work if you use the same proxy instance everywhere:

```
database = peewee.Proxy()

class MyModel(peewee.Model):
    # ...
    class Meta:
         database = database

objects = peewee_async.Manager(database)

# ...

database.init(real_database)
```

**Comment by dgelvin** [comment]
I wasn't able to instantiate the Manager using the Proxy:
```
Error
Traceback (most recent call last):
  File "/home/dgelvin/Desktop/peewee-async-test/env/lib/python3.5/site-packages/asynctest/case.py", line 257, in run
    self._setUp()
  File "/home/dgelvin/Desktop/peewee-async-test/env/lib/python3.5/site-packages/asynctest/case.py", line 217, in _setUp
    self.setUp()
  File "/home/dgelvin/Desktop/peewee-async-test/test_peewee.py", line 53, in setUp
    Database.init_db(database_name='pwt', host='172.17.0.2', user='postgres', password='abc123')
  File "/home/dgelvin/Desktop/peewee-async-test/test_peewee.py", line 21, in init_db
    cls.aio_manager = Manager(cls.database)
  File "/home/dgelvin/Desktop/peewee-async-test/env/lib/python3.5/site-packages/peewee_async.py", line 112, in __init__
    self.database.loop = self.loop
  File "/home/dgelvin/Desktop/peewee-async-test/env/lib/python3.5/site-packages/peewee.py", line 412, in __setattr__
    raise AttributeError('Cannot set attribute on proxy.')
AttributeError: Cannot set attribute on proxy.
```

Same issue with trying to set `database.allow_sync`- that will also raise `AttributeError('Cannot set attribute on proxy.')`.

**Comment by rudyryk** [comment]
@dgelvin Ah, I see, got it :) That's true - `peewee.Proxy` is limited to getting attributes and doesn't proxies setting attributes. I was actually surprised by that limitation. Thank you!

I'll think how we may handle that.

Btw, for now, I'm using my own subclass of `peewee.Proxy` like that:

```python
class ProxyDatabase(peewee.Proxy):
    def __setattr__(self, attr, value):
        if attr in self.__slots__:
            return super().__setattr__(attr, value)
        else:
            return setattr(self.obj, attr, value)
```

**Comment by rudyryk** [comment]
@dgelvin David, I've added init hooks and now it's OK to set up `Manager` directly with `peewee.Proxy`. Not sure whether we need extra checks on every execute, probably not :)

**Comment by dgelvin** [comment]
Thanks for the new release- works perfectly.  I've created a new pull request to remove the now unnecessary check for Proxy.

**Comment by dgelvin** [comment]
So I'm still having some problems- I've created a [new issue](https://github.com/05bit/peewee-async/issues/30).

**Pull request merged**
