### PR TITLE
missing cursor release

### PR DESCRIPTION
**Pull request by mrbox**

### CODE REVIEW

**Comment by mrbox** [comment]
Whoops, while rebasing I've doubled some commits, let me re-work this

**Comment by rudyryk** [comment]
@mrbox Hi Jakub! :) So, is it OK now?

**Comment by mrbox** [comment]
Hi Alex :) Don't merge it yet- apparently locally it's not yet working as good as I expect it to work. Will ping you when I'm sure what happens- if it local env or something with code :)

**Comment by rudyryk** [comment]
Ok :) Closing it for now then, btw pushed a bunch of updates recently :)

**Pull request closed without merging**
